name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start container with '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Kimigayo OS Version
      description: "Output of: cat /etc/os-release"
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: variant
    attributes:
      label: Image Variant
      description: Which image variant are you using?
      options:
        - minimal
        - standard
        - extended
        - custom
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: "Output of: uname -m"
      options:
        - x86_64
        - aarch64 (ARM64)
        - other
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Container Runtime
      description: Which container runtime are you using?
      options:
        - Docker
        - Podman
        - containerd
        - Other
    validations:
      required: true

  - type: input
    id: runtime-version
    attributes:
      label: Container Runtime Version
      description: "e.g., docker version or podman version"
      placeholder: "e.g., Docker 24.0.7"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste relevant log output (if any)
      render: shell
      placeholder: Paste logs here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context...
    validations:
      required: false

  - type: dropdown
    id: workaround
    attributes:
      label: Workaround Available?
      description: Have you found a workaround?
      options:
        - "No"
        - "Yes"
    validations:
      required: false

  - type: textarea
    id: workaround-details
    attributes:
      label: Workaround Details
      description: If yes, please describe the workaround
      placeholder: Describe workaround...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all required information
          required: true
        - label: I am using the latest version of Kimigayo OS
          required: false
