name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "feature-request", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        As a [user type],
        I want [goal],
        So that [benefit].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe alternatives...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component would this feature affect?
      options:
        - Core OS
        - Package Manager (isn)
        - Init System (OpenRC)
        - Networking
        - Security
        - Build System
        - CI/CD
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Assessment)
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (important for my use case)
        - Medium (would be nice to have)
        - Low (future consideration)
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this introduce breaking changes?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: breaking-details
    attributes:
      label: Breaking Change Details
      description: If yes, please describe the breaking changes
      placeholder: Describe breaking changes...
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: Describe use case...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this would work
      placeholder: |
        # Example usage
        $ command --new-flag

        # Expected output
        ...
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to similar features in other projects or documentation
      placeholder: |
        - https://example.com/similar-feature
        - Related RFC: ...
    validations:
      required: false

  - type: dropdown
    id: contribute
    attributes:
      label: Willing to Contribute?
      description: Are you willing to contribute this feature?
      options:
        - "Yes, I can implement this"
        - "Yes, with guidance"
        - "No, but I can test"
        - "No"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I understand this is a request and may not be implemented immediately
          required: true
