name: 🔒 Security Vulnerability (Private)
description: Report a security vulnerability (will be kept private)
title: "[Security]: "
labels: ["security", "vulnerability"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: Private Security Reporting

        **DO NOT** report security vulnerabilities in public issues!

        Instead, please use GitHub's [Private Security Advisories](../../security/advisories/new) feature.

        This issue template is for security-related **improvements** only, not for reporting vulnerabilities.

        ---

        ### How to Report a Security Vulnerability

        1. Go to the [Security tab](../../security)
        2. Click "Report a vulnerability"
        3. Fill out the private advisory form
        4. Our team will respond within 24 hours

        ### Our Security Policy

        Please review our [Security Policy](../../security/policy) for:
        - Supported versions
        - Vulnerability disclosure process
        - Security update timeline

        ---

        If this is a **security improvement** (not a vulnerability), please continue with this form.

  - type: dropdown
    id: type
    attributes:
      label: Security Improvement Type
      description: What type of security improvement is this?
      options:
        - Security hardening suggestion
        - Security feature request
        - Security documentation improvement
        - Security audit request
        - Other security improvement
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security improvement
      placeholder: Describe the improvement...
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Security Rationale
      description: Why would this improve security?
      placeholder: Explain the security benefits...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component would this affect?
      options:
        - Kernel security
        - System hardening
        - Package signing
        - Network security
        - Access control
        - Encryption
        - Build process
        - CI/CD pipeline
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestion
      description: How could this be implemented?
      placeholder: Describe implementation approach...
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to security best practices, standards, or similar implementations
      placeholder: |
        - CIS Benchmark: https://...
        - NIST guidelines: https://...
        - Similar implementation: https://...
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm
      options:
        - label: This is NOT a vulnerability report (I will use Security Advisories for that)
          required: true
        - label: I have reviewed the security policy
          required: true
        - label: I have searched for existing similar issues
          required: true
